name: Terragrunt CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terragrunt:
    name: Terragrunt Plan/Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.7

      - name: Install Terragrunt
        run: |
          TG_VERSION=0.86.1
          wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TG_VERSION}/terragrunt_linux_amd64
          chmod +x terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-session-name: GithubActions
          role-to-assume: arn:aws:iam::635566486216:role/GitHubActionsDeployRole

      - name: Terragrunt Plan
        working-directory: environments
        run: terragrunt run-all plan

      - name: Terragrunt Apply
        working-directory: environments
        run: terragrunt run-all apply

